BASE_THRESHOLDS = {
    "sentence_similarity_threshold": 0.20,
    "usr_partial_threshold": 0.01,
    "usr_invalid_threshold": 0.50,
}


EXPERIMENTS = {

    # =========================================================
    # BASELINES
    # =========================================================

    "baseline_flat_openai": {
        "hybrid_retrieval": False,
        "citation_prompt": False,
        "sentence_validation": False,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "flat",
        "embedding_model": "openai",
    },
    "baseline_sections_openai": {
        "hybrid_retrieval": False,
        "citation_prompt": False,
        "sentence_validation": False,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "sections",
        "embedding_model": "openai",
    },
    "baseline_sections_e5": {
        "hybrid_retrieval": False,
        "citation_prompt": False,
        "sentence_validation": False,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
    },
    "baseline_sections_medcpt": {
        "hybrid_retrieval": False,
        "citation_prompt": False,
        "sentence_validation": False,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "sections",
        "embedding_model": "medcpt",
    },

    # =========================================================
    # PROPUESTA 1
    # =========================================================

    "propuesta_1_full_openai": {
        "hybrid_retrieval": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "propuesta_1_full_e5": {
        "hybrid_retrieval": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "propuesta_1_full_medcpt": {
        "hybrid_retrieval": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "sections",
        "embedding_model": "medcpt",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },

    # =========================================================
    # PROPUESTA 2
    # =========================================================

    "propuesta_2_full_openai": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "propuesta_2_full_e5": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "propuesta_2_full_medcpt": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "medcpt",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    # =========================================================
    # NOISE ROBUSTNESS - PROPUESTA 1
    # =========================================================

    "propuesta_1_full_openai_noisy": {
        "hybrid_retrieval": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "noise_injection": True,
        "noise_chunks": 2,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "propuesta_1_full_e5_noisy": {
        "hybrid_retrieval": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "noise_injection": True,
        "noise_chunks": 2,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "propuesta_1_full_medcpt_noisy": {
        "hybrid_retrieval": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "dynamic_k": False,
        "refine_generation": False,
        "chunking_variant": "sections",
        "embedding_model": "medcpt",
        "noise_injection": True,
        "noise_chunks": 2,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },

    # =========================================================
    # NOISE ROBUSTNESS - PROPUESTA 2
    # =========================================================

    "propuesta_2_full_openai_noisy": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "noise_injection": True,
        "noise_chunks": 2,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "propuesta_2_full_e5_noisy": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "noise_injection": True,
        "noise_chunks": 2,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "propuesta_2_full_medcpt_noisy": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "medcpt",
        "noise_injection": True,
        "noise_chunks": 2,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "p2_openai_noise_0": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "noise_injection": False,
        "noise_chunks": 0,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "p2_openai_noise_2": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "noise_injection": True,
        "noise_chunks": 2,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "p2_openai_noise_4": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "noise_injection": True,
        "noise_chunks": 4,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "p2_openai_noise_8": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "noise_injection": True,
        "noise_chunks": 8,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "p2_openai_noise_16": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "noise_injection": True,
        "noise_chunks": 16,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    # PRUEBA KNOWLEDGE NOISE
    "p2_openai_knowledge_noise": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "index_suffix": "corrupted",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "p2_openai_knowledge_noise_no_refine": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": False,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "index_suffix": "corrupted",
        "sentence_similarity_threshold": 0.20,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.50,
    },
    "p2_openai_knowledge_noise_no_validation": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": False,
        "refine_generation": False,
        "multi_validation": False,
        "chunking_variant": "sections",
        "embedding_model": "openai",
        "index_suffix": "corrupted",
    },
    "p2_e5_noise_0": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "noise_injection": False,
        "noise_chunks": 0,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.2,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.5,
    },
    "p2_e5_noise_2": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "noise_injection": True,
        "noise_chunks": 2,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.2,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.5,
    },
    "p2_e5_noise_4": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "noise_injection": True,
        "noise_chunks": 4,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.2,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.5,
    },
    "p2_e5_noise_8": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "noise_injection": True,
        "noise_chunks": 8,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.2,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.5,
    },
    "p2_e5_noise_16": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "noise_injection": True,
        "noise_chunks": 16,
        "noise_seed": 42,
        "noise_placement": "end",
        "sentence_similarity_threshold": 0.2,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.5,
    },
    "p2_e5_knowledge_noise_no_validation": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": False,
        "refine_generation": False,
        "multi_validation": False,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "index_suffix": "corrupted",
    },
    "p2_e5_knowledge_noise": {
        "hybrid_retrieval": True,
        "dynamic_k": True,
        "citation_prompt": True,
        "sentence_validation": True,
        "refine_generation": True,
        "multi_validation": True,
        "chunking_variant": "sections",
        "embedding_model": "multilingual_e5",
        "index_suffix": "corrupted",
        "sentence_similarity_threshold": 0.2,
        "usr_partial_threshold": 0.01,
        "usr_invalid_threshold": 0.5,
    },
}